/* Generated By:JavaCC: Do not edit this line. MysqlParserTreeConstants.java Version 4.1d1 */
package com.meidusa.amoeba.mysql.parser.sql;

public interface MysqlParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=1f5f20f9b82a5e03a1e1d0b8842c4c0c (do not edit this line) */
