/* Generated By:JJTree: Do not edit this line. ASTStart.java */
package com.meidusa.amoeba.sqljep;


/**
 * Start Node
 */
public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Parser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException
  {
    return visitor.visit(this, data);
  }
}
