/* Generated By:JJTree: Do not edit this line. .\ParserTreeConstants.java */

package com.meidusa.amoeba.sqljep;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTVARNODE = 3;
  public int JJTARRAY = 4;
  public int JJTCONSTANT = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "FunNode",
    "VarNode",
    "Array",
    "Constant",
  };
}
